//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^3[47][0-9]{13}$.
        /// </summary>
        public static string RegexCreditCardAmex {
            get {
                return ResourceManager.GetString("RegexCreditCardAmex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^3(?:0[0-5]|[68][0-9])[0-9]{11}$.
        /// </summary>
        public static string RegexCreditCardDinersClub {
            get {
                return ResourceManager.GetString("RegexCreditCardDinersClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^6(?:011|5[0-9]{2})[0-9]{12}$.
        /// </summary>
        public static string RegexCreditCardDiscover {
            get {
                return ResourceManager.GetString("RegexCreditCardDiscover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?:2131|1800|35\d{3})\d{11}$.
        /// </summary>
        public static string RegexCreditCardJCB {
            get {
                return ResourceManager.GetString("RegexCreditCardJCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^5[1-5][0-9]{14}$.
        /// </summary>
        public static string RegexCreditCardMasterCard {
            get {
                return ResourceManager.GetString("RegexCreditCardMasterCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^4[0-9]{12}(?:[0-9]{3})?$.
        /// </summary>
        public static string RegexCreditCardVisa {
            get {
                return ResourceManager.GetString("RegexCreditCardVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string TextAboutUs {
            get {
                return ResourceManager.GetString("TextAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string TextAccount {
            get {
                return ResourceManager.GetString("TextAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account activation.
        /// </summary>
        public static string TextAccountActivation {
            get {
                return ResourceManager.GetString("TextAccountActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account deactivation.
        /// </summary>
        public static string TextAccountDeactivation {
            get {
                return ResourceManager.GetString("TextAccountDeactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string TextAdministration {
            get {
                return ResourceManager.GetString("TextAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket.
        /// </summary>
        public static string TextBasket {
            get {
                return ResourceManager.GetString("TextBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product has been added to basket successfully .
        /// </summary>
        public static string TextBasketAddSuccess {
            get {
                return ResourceManager.GetString("TextBasketAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket is empty.
        /// </summary>
        public static string TextBasketEmpty {
            get {
                return ResourceManager.GetString("TextBasketEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string TextChangePassword {
            get {
                return ResourceManager.GetString("TextChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string TextCheckout {
            get {
                return ResourceManager.GetString("TextCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation code.
        /// </summary>
        public static string TextConfirmationCode {
            get {
                return ResourceManager.GetString("TextConfirmationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this record?.
        /// </summary>
        public static string TextConfirmDelete {
            get {
                return ResourceManager.GetString("TextConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this file?.
        /// </summary>
        public static string TextConfirmDeleteAttachment {
            get {
                return ResourceManager.GetString("TextConfirmDeleteAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this record will delete all subrecords. Do you want to continue?.
        /// </summary>
        public static string TextConfirmDeleteRecursive {
            get {
                return ResourceManager.GetString("TextConfirmDeleteRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string TextContact {
            get {
                return ResourceManager.GetString("TextContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website contact form email.
        /// </summary>
        public static string TextContactFormEmail {
            get {
                return ResourceManager.GetString("TextContactFormEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry something went wrong.
        /// </summary>
        public static string TextError {
            get {
                return ResourceManager.GetString("TextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery ID is not unique.
        /// </summary>
        public static string TextFacebookGalleryIDNotUniq {
            get {
                return ResourceManager.GetString("TextFacebookGalleryIDNotUniq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string TextFAQ {
            get {
                return ResourceManager.GetString("TextFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string TextNo {
            get {
                return ResourceManager.GetString("TextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string TextOrders {
            get {
                return ResourceManager.GetString("TextOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery.
        /// </summary>
        public static string TextPasswordRecovery {
            get {
                return ResourceManager.GetString("TextPasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment failed.
        /// </summary>
        public static string TextPaymentFailed {
            get {
                return ResourceManager.GetString("TextPaymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Success.
        /// </summary>
        public static string TextPaymentSuccess {
            get {
                return ResourceManager.GetString("TextPaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all fields.
        /// </summary>
        public static string TextPleaseFillAllFields {
            get {
                return ResourceManager.GetString("TextPleaseFillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string TextProducts {
            get {
                return ResourceManager.GetString("TextProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string TextProfile {
            get {
                return ResourceManager.GetString("TextProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string TextResetPassword {
            get {
                return ResourceManager.GetString("TextResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Notification.
        /// </summary>
        public static string TextSaleNotification {
            get {
                return ResourceManager.GetString("TextSaleNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string TextSignIn {
            get {
                return ResourceManager.GetString("TextSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string TextSignOut {
            get {
                return ResourceManager.GetString("TextSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string TextSignUp {
            get {
                return ResourceManager.GetString("TextSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug is not unique.
        /// </summary>
        public static string TextSlugNotUniq {
            get {
                return ResourceManager.GetString("TextSlugNotUniq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been saved successfully.
        /// </summary>
        public static string TextSuccess {
            get {
                return ResourceManager.GetString("TextSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string TextYes {
            get {
                return ResourceManager.GetString("TextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation code is invalid.
        /// </summary>
        public static string ValidateConfirmationCodeNotValid {
            get {
                return ResourceManager.GetString("ValidateConfirmationCodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is not found in our system.
        /// </summary>
        public static string ValidateEmailNotRegistered {
            get {
                return ResourceManager.GetString("ValidateEmailNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid recovery code.
        /// </summary>
        public static string ValidateRecoveryCodeNotValid {
            get {
                return ResourceManager.GetString("ValidateRecoveryCodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already taken.
        /// </summary>
        public static string ValidationEmailNotUnique {
            get {
                return ResourceManager.GetString("ValidationEmailNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid.
        /// </summary>
        public static string ValidationEmailNotValid {
            get {
                return ResourceManager.GetString("ValidationEmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ZIP and state combination.
        /// </summary>
        public static string ValidationInvalidZIPSndStateCombination {
            get {
                return ResourceManager.GetString("ValidationInvalidZIPSndStateCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid old password.
        /// </summary>
        public static string ValidationOldPasswordNotMatch {
            get {
                return ResourceManager.GetString("ValidationOldPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 character long.
        /// </summary>
        public static string ValidationPasswordLength {
            get {
                return ResourceManager.GetString("ValidationPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string ValidationPasswordsNotMatch {
            get {
                return ResourceManager.GetString("ValidationPasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one letter and one number.
        /// </summary>
        public static string ValidationPasswordStrength {
            get {
                return ResourceManager.GetString("ValidationPasswordStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter category caption.
        /// </summary>
        public static string ValidationRequiredCategoryCaption {
            get {
                return ResourceManager.GetString("ValidationRequiredCategoryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is required.
        /// </summary>
        public static string ValidationRequiredField {
            get {
                return ResourceManager.GetString("ValidationRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter page title.
        /// </summary>
        public static string ValidationRequiredPageTitle {
            get {
                return ResourceManager.GetString("ValidationRequiredPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string ValidationUserInvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("ValidationUserInvalidUsernameOrPassword", resourceCulture);
            }
        }
    }
}
