//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +995 032 256 5555.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to youtu(?:\.be|be\.com)/(?:.*v(?:/|=)|(?:.*/)?)([a-zA-Z0-9-_]+).
        /// </summary>
        public static string RegexYoutubeVideoID {
            get {
                return ResourceManager.GetString("RegexYoutubeVideoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Company.
        /// </summary>
        public static string TextAboutCompany {
            get {
                return ResourceManager.GetString("TextAboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for securities, issuers, news and documents.
        /// </summary>
        public static string TextAboveSearchInput {
            get {
                return ResourceManager.GetString("TextAboveSearchInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Activation.
        /// </summary>
        public static string TextAccountActivation {
            get {
                return ResourceManager.GetString("TextAccountActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string TextActivate {
            get {
                return ResourceManager.GetString("TextActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Code.
        /// </summary>
        public static string TextActivationCode {
            get {
                return ResourceManager.GetString("TextActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration completed successfully. Activation code has been sent to your email..
        /// </summary>
        public static string TextActivationDescription {
            get {
                return ResourceManager.GetString("TextActivationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Building.
        /// </summary>
        public static string TextAddBuilding {
            get {
                return ResourceManager.GetString("TextAddBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Flat.
        /// </summary>
        public static string TextAddFlat {
            get {
                return ResourceManager.GetString("TextAddFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Floor.
        /// </summary>
        public static string TextAddFloor {
            get {
                return ResourceManager.GetString("TextAddFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string TextAddress {
            get {
                return ResourceManager.GetString("TextAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Address.
        /// </summary>
        public static string TextAddressActual {
            get {
                return ResourceManager.GetString("TextAddressActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Trades.
        /// </summary>
        public static string TextAllDeals {
            get {
                return ResourceManager.GetString("TextAllDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Trades.
        /// </summary>
        public static string TextAllDealsQuantity {
            get {
                return ResourceManager.GetString("TextAllDealsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admitted Securities.
        /// </summary>
        public static string TextAllowedSecurities {
            get {
                return ResourceManager.GetString("TextAllowedSecurities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All results.
        /// </summary>
        public static string TextAllResults {
            get {
                return ResourceManager.GetString("TextAllResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string TextAnalysis {
            get {
                return ResourceManager.GetString("TextAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architect.
        /// </summary>
        public static string TextArchitect {
            get {
                return ResourceManager.GetString("TextArchitect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string TextArchive {
            get {
                return ResourceManager.GetString("TextArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        public static string TextAsk {
            get {
                return ResourceManager.GetString("TextAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighted Average Price.
        /// </summary>
        public static string TextAverage {
            get {
                return ResourceManager.GetString("TextAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance sheet.
        /// </summary>
        public static string TextBalanceSheet {
            get {
                return ResourceManager.GetString("TextBalanceSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid.
        /// </summary>
        public static string TextBid {
            get {
                return ResourceManager.GetString("TextBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string TextBoard {
            get {
                return ResourceManager.GetString("TextBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonds.
        /// </summary>
        public static string TextBonds {
            get {
                return ResourceManager.GetString("TextBonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brokerage Firms.
        /// </summary>
        public static string TextBrokerCompanies {
            get {
                return ResourceManager.GetString("TextBrokerCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} brokerage companies participated in trading session..
        /// </summary>
        public static string TextBrokerCompaniesParticipated {
            get {
                return ResourceManager.GetString("TextBrokerCompaniesParticipated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        public static string TextBrokerCompanyIssueDate {
            get {
                return ResourceManager.GetString("TextBrokerCompanyIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string TextBrokerCompanyLicense {
            get {
                return ResourceManager.GetString("TextBrokerCompanyLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brokers.
        /// </summary>
        public static string TextBrokers {
            get {
                return ResourceManager.GetString("TextBrokers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Address.
        /// </summary>
        public static string TextBusinessAddress {
            get {
                return ResourceManager.GetString("TextBusinessAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string TextBuy {
            get {
                return ResourceManager.GetString("TextBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statements.
        /// </summary>
        public static string TextCalculations {
            get {
                return ResourceManager.GetString("TextCalculations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitalization.
        /// </summary>
        public static string TextCapitalization {
            get {
                return ResourceManager.GetString("TextCapitalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Capitalization.
        /// </summary>
        public static string TextCapitalizationTotal {
            get {
                return ResourceManager.GetString("TextCapitalizationTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption is required.
        /// </summary>
        public static string TextCaptionRequired {
            get {
                return ResourceManager.GetString("TextCaptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string TextCategory {
            get {
                return ResourceManager.GetString("TextCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string TextChange {
            get {
                return ResourceManager.GetString("TextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes are saved.
        /// </summary>
        public static string TextChangesSaved {
            get {
                return ResourceManager.GetString("TextChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charter Capital.
        /// </summary>
        public static string TextCharterCapital {
            get {
                return ResourceManager.GetString("TextCharterCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment has been succeeded.
        /// </summary>
        public static string TextCheckoutSuccess {
            get {
                return ResourceManager.GetString("TextCheckoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string TextChoose {
            get {
                return ResourceManager.GetString("TextChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Securities.
        /// </summary>
        public static string TextChooseSecurities {
            get {
                return ResourceManager.GetString("TextChooseSecurities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Price.
        /// </summary>
        public static string TextClosingPrice {
            get {
                return ResourceManager.GetString("TextClosingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string TextCode {
            get {
                return ResourceManager.GetString("TextCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is not unique.
        /// </summary>
        public static string TextCodeNotUniq {
            get {
                return ResourceManager.GetString("TextCodeNotUniq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string TextCodeRequired {
            get {
                return ResourceManager.GetString("TextCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string TextCollapse {
            get {
                return ResourceManager.GetString("TextCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string TextComment {
            get {
                return ResourceManager.GetString("TextComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparative Analysis.
        /// </summary>
        public static string TextCompareAnalysis {
            get {
                return ResourceManager.GetString("TextCompareAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed projects.
        /// </summary>
        public static string TextCompletedProjects {
            get {
                return ResourceManager.GetString("TextCompletedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this item?.
        /// </summary>
        public static string TextConfirmDelete {
            get {
                return ResourceManager.GetString("TextConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this file?.
        /// </summary>
        public static string TextConfirmDeleteAttachment {
            get {
                return ResourceManager.GetString("TextConfirmDeleteAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this record?.
        /// </summary>
        public static string TextConfirmDeleteRecord {
            get {
                return ResourceManager.GetString("TextConfirmDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this page will delete all subordinated pages. Do you want to continue?.
        /// </summary>
        public static string TextConfirmDeleteRecursive {
            get {
                return ResourceManager.GetString("TextConfirmDeleteRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action can be harmful, do you want to proceed?.
        /// </summary>
        public static string TextConfirmDeleteSecond {
            get {
                return ResourceManager.GetString("TextConfirmDeleteSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to restore this item?.
        /// </summary>
        public static string TextConfirmRestore {
            get {
                return ResourceManager.GetString("TextConfirmRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to send newsletters?.
        /// </summary>
        public static string TextConfirmSendNewsletters {
            get {
                return ResourceManager.GetString("TextConfirmSendNewsletters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string TextContact {
            get {
                return ResourceManager.GetString("TextContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has successfully been sent.
        /// </summary>
        public static string TextContactFormSendSuccess {
            get {
                return ResourceManager.GetString("TextContactFormSendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact message could not be sent. Please type correct email address..
        /// </summary>
        public static string TextContactMessageNotSent {
            get {
                return ResourceManager.GetString("TextContactMessageNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuing operations.
        /// </summary>
        public static string TextContinuingOperations {
            get {
                return ResourceManager.GetString("TextContinuingOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string TextCost {
            get {
                return ResourceManager.GetString("TextCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Value (GEL).
        /// </summary>
        public static string TextCostOfGelIssuedSecurities {
            get {
                return ResourceManager.GetString("TextCostOfGelIssuedSecurities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Value (GEL).
        /// </summary>
        public static string TextCostOfIssuedSecuritiesWithCurrency {
            get {
                return ResourceManager.GetString("TextCostOfIssuedSecuritiesWithCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Value (USD).
        /// </summary>
        public static string TextCostOfUsdIssuedSecurities {
            get {
                return ResourceManager.GetString("TextCostOfUsdIssuedSecurities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maturity Date.
        /// </summary>
        public static string TextCoverDate {
            get {
                return ResourceManager.GetString("TextCoverDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string TextCreatedBy {
            get {
                return ResourceManager.GetString("TextCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string TextCurrency {
            get {
                return ResourceManager.GetString("TextCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEL.
        /// </summary>
        public static string TextCurrencyGel {
            get {
                return ResourceManager.GetString("TextCurrencyGel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEL Exchange Rates.
        /// </summary>
        public static string TextCurrencyRates {
            get {
                return ResourceManager.GetString("TextCurrencyRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        public static string TextCurrencyUsd {
            get {
                return ResourceManager.GetString("TextCurrencyUsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current price.
        /// </summary>
        public static string TextCurrentPrice {
            get {
                return ResourceManager.GetString("TextCurrentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TextDate {
            get {
                return ResourceManager.GetString("TextDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string TextDateFrom {
            get {
                return ResourceManager.GetString("TextDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string TextDateTo {
            get {
                return ResourceManager.GetString("TextDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Trade.
        /// </summary>
        public static string TextDealType {
            get {
                return ResourceManager.GetString("TextDealType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TextDescription {
            get {
                return ResourceManager.GetString("TextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinued operations.
        /// </summary>
        public static string TextDiscontinuedOperations {
            get {
                return ResourceManager.GetString("TextDiscontinuedOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download plan.
        /// </summary>
        public static string TextDownloadPlan {
            get {
                return ResourceManager.GetString("TextDownloadPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string TextEmail {
            get {
                return ResourceManager.GetString("TextEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer.
        /// </summary>
        public static string TextEmployer {
            get {
                return ResourceManager.GetString("TextEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position/Title.
        /// </summary>
        public static string TextEmploymentJobPosition {
            get {
                return ResourceManager.GetString("TextEmploymentJobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TextEmploymentStatus {
            get {
                return ResourceManager.GetString("TextEmploymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrance.
        /// </summary>
        public static string TextEntrance {
            get {
                return ResourceManager.GetString("TextEntrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, something went wrong.
        /// </summary>
        public static string TextError {
            get {
                return ResourceManager.GetString("TextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        public static string TextExpand {
            get {
                return ResourceManager.GetString("TextExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string TextExpirationDate {
            get {
                return ResourceManager.GetString("TextExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string TextFail {
            get {
                return ResourceManager.GetString("TextFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string TextFaq {
            get {
                return ResourceManager.GetString("TextFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string TextFiles {
            get {
                return ResourceManager.GetString("TextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TextFirstname {
            get {
                return ResourceManager.GetString("TextFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat.
        /// </summary>
        public static string TextFlat {
            get {
                return ResourceManager.GetString("TextFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat area.
        /// </summary>
        public static string TextFlatArea {
            get {
                return ResourceManager.GetString("TextFlatArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat&apos;s Price.
        /// </summary>
        public static string TextFlatPrice {
            get {
                return ResourceManager.GetString("TextFlatPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat properties.
        /// </summary>
        public static string TextFlatProperties {
            get {
                return ResourceManager.GetString("TextFlatProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string TextFloor {
            get {
                return ResourceManager.GetString("TextFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 71 Vaja Pshavela,&lt;br /&gt;
        ///                            10th Block,&lt;br /&gt;
        ///                            7th Floor,&lt;br /&gt;
        ///                            Tbilisi 0186.
        /// </summary>
        public static string TextFooterContactBlock {
            get {
                return ResourceManager.GetString("TextFooterContactBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founders.
        /// </summary>
        public static string TextFounders {
            get {
                return ResourceManager.GetString("TextFounders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string TextFree {
            get {
                return ResourceManager.GetString("TextFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From 01/01/2017.
        /// </summary>
        public static string TextFrom01012017 {
            get {
                return ResourceManager.GetString("TextFrom01012017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full area.
        /// </summary>
        public static string TextFullArea {
            get {
                return ResourceManager.GetString("TextFullArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trades in GEL.
        /// </summary>
        public static string TextGelSession {
            get {
                return ResourceManager.GetString("TextGelSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trades in GEL.
        /// </summary>
        public static string TextGelSessionHours {
            get {
                return ResourceManager.GetString("TextGelSessionHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string TextGraphic {
            get {
                return ResourceManager.GetString("TextGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1} (Total {2} Records).
        /// </summary>
        public static string TextGridPager {
            get {
                return ResourceManager.GetString("TextGridPager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSE Updates.
        /// </summary>
        public static string TextGseUpdates {
            get {
                return ResourceManager.GetString("TextGseUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSX Index.
        /// </summary>
        public static string TextGsxTradeIndex {
            get {
                return ResourceManager.GetString("TextGsxTradeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TextHome {
            get {
                return ResourceManager.GetString("TextHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income statement.
        /// </summary>
        public static string TextIncomeStatement {
            get {
                return ResourceManager.GetString("TextIncomeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field of Activity.
        /// </summary>
        public static string TextIndustry {
            get {
                return ResourceManager.GetString("TextIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is active.
        /// </summary>
        public static string TextIsActive {
            get {
                return ResourceManager.GetString("TextIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISIN.
        /// </summary>
        public static string TextISIN {
            get {
                return ResourceManager.GetString("TextISIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer.
        /// </summary>
        public static string TextIssuer {
            get {
                return ResourceManager.GetString("TextIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer code is not unique.
        /// </summary>
        public static string TextIssuerCodeNotUniq {
            get {
                return ResourceManager.GetString("TextIssuerCodeNotUniq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer code is required.
        /// </summary>
        public static string TextIssuerCodeRequired {
            get {
                return ResourceManager.GetString("TextIssuerCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        public static string TextIssuerDirector {
            get {
                return ResourceManager.GetString("TextIssuerDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string TextIssuerPhone {
            get {
                return ResourceManager.GetString("TextIssuerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuers.
        /// </summary>
        public static string TextIssuers {
            get {
                return ResourceManager.GetString("TextIssuers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisory Board Chairman.
        /// </summary>
        public static string TextIssuerSupervisoryBoardChairman {
            get {
                return ResourceManager.GetString("TextIssuerSupervisoryBoardChairman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string TextIssuerWebsite {
            get {
                return ResourceManager.GetString("TextIssuerWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 5 Trades.
        /// </summary>
        public static string TextLastFiveDayDeals {
            get {
                return ResourceManager.GetString("TextLastFiveDayDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string TextLastname {
            get {
                return ResourceManager.GetString("TextLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Price.
        /// </summary>
        public static string TextLastPrice {
            get {
                return ResourceManager.GetString("TextLastPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} brokerage firms participated in the trading session.
        /// </summary>
        public static string TextLastTradeCompatitorsCount {
            get {
                return ResourceManager.GetString("TextLastTradeCompatitorsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Trading Session.
        /// </summary>
        public static string TextLastTradeSession {
            get {
                return ResourceManager.GetString("TextLastTradeSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Session Results.
        /// </summary>
        public static string TextLastTradeSessionResults {
            get {
                return ResourceManager.GetString("TextLastTradeSessionResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string TextLicense {
            get {
                return ResourceManager.GetString("TextLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string TextLinks {
            get {
                return ResourceManager.GetString("TextLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For OTC trades before 31/12/2016, please visit &lt;a href=&quot;{0}&quot;&gt;archive&lt;/a&gt;..
        /// </summary>
        public static string TextLinkToOtcTradesArchive {
            get {
                return ResourceManager.GetString("TextLinkToOtcTradesArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing.
        /// </summary>
        public static string TextListing {
            get {
                return ResourceManager.GetString("TextListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Listing.
        /// </summary>
        public static string TextListingA {
            get {
                return ResourceManager.GetString("TextListingA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B Listing.
        /// </summary>
        public static string TextListingB {
            get {
                return ResourceManager.GetString("TextListingB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listed Companies.
        /// </summary>
        public static string TextListingCompanies {
            get {
                return ResourceManager.GetString("TextListingCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string TextLocation {
            get {
                return ResourceManager.GetString("TextLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string TextLogin {
            get {
                return ResourceManager.GetString("TextLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string TextLogout {
            get {
                return ResourceManager.GetString("TextLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        public static string TextLookMore {
            get {
                return ResourceManager.GetString("TextLookMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TextMain {
            get {
                return ResourceManager.GetString("TextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string TextManagement {
            get {
                return ResourceManager.GetString("TextManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Updates.
        /// </summary>
        public static string TextMarketUpdates {
            get {
                return ResourceManager.GetString("TextMarketUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string TextMaxPrice {
            get {
                return ResourceManager.GetString("TextMaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string TextMinPrice {
            get {
                return ResourceManager.GetString("TextMinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string TextMonth {
            get {
                return ResourceManager.GetString("TextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Page.
        /// </summary>
        public static string TextMyPage {
            get {
                return ResourceManager.GetString("TextMyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TextName {
            get {
                return ResourceManager.GetString("TextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net interest.
        /// </summary>
        public static string TextNetInterest {
            get {
                return ResourceManager.GetString("TextNetInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string TextNews {
            get {
                return ResourceManager.GetString("TextNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletters.
        /// </summary>
        public static string TextNewsletters {
            get {
                return ResourceManager.GetString("TextNewsletters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter send process has started successfully.
        /// </summary>
        public static string TextNewsletterSendProcessStarted {
            get {
                return ResourceManager.GetString("TextNewsletterSendProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string TextNext {
            get {
                return ResourceManager.GetString("TextNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Session.
        /// </summary>
        public static string TextNextSession {
            get {
                return ResourceManager.GetString("TextNextSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string TextNo {
            get {
                return ResourceManager.GetString("TextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        public static string TextNoData {
            get {
                return ResourceManager.GetString("TextNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal Value.
        /// </summary>
        public static string TextNominal {
            get {
                return ResourceManager.GetString("TextNominal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal Currency.
        /// </summary>
        public static string TextNominalCurrency {
            get {
                return ResourceManager.GetString("TextNominalCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found.
        /// </summary>
        public static string TextNothingFound {
            get {
                return ResourceManager.GetString("TextNothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admitted to Trading.
        /// </summary>
        public static string TextNotListingCompanies {
            get {
                return ResourceManager.GetString("TextNotListingCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of Issue.
        /// </summary>
        public static string TextNumberOfIssuedSecurities {
            get {
                return ResourceManager.GetString("TextNumberOfIssuedSecurities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string TextNumberOfSecurities {
            get {
                return ResourceManager.GetString("TextNumberOfSecurities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string TextOldPassword {
            get {
                return ResourceManager.GetString("TextOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span&gt;This website is under the testing mode.&lt;/span&gt; &lt;a href=&quot;http://old.gse.ge/&quot; target=&quot;_blank&quot;&gt;To view older version, please follow the link.&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string TextOldWebsite {
            get {
                return ResourceManager.GetString("TextOldWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string TextOpeningPrice {
            get {
                return ResourceManager.GetString("TextOpeningPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating Profit/(Loss).
        /// </summary>
        public static string TextOperatingProfitOrLoss {
            get {
                return ResourceManager.GetString("TextOperatingProfitOrLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTC.
        /// </summary>
        public static string TextOtc {
            get {
                return ResourceManager.GetString("TextOtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTC Trades.
        /// </summary>
        public static string TextOtcTrades {
            get {
                return ResourceManager.GetString("TextOtcTrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otc Trades Archive.
        /// </summary>
        public static string TextOtcTradesArchive {
            get {
                return ResourceManager.GetString("TextOtcTradesArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string TextPagerFirst {
            get {
                return ResourceManager.GetString("TextPagerFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string TextPagerLast {
            get {
                return ResourceManager.GetString("TextPagerLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string TextPagerNext {
            get {
                return ResourceManager.GetString("TextPagerNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string TextPagerPrevious {
            get {
                return ResourceManager.GetString("TextPagerPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size.
        /// </summary>
        public static string TextPageSize {
            get {
                return ResourceManager.GetString("TextPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        public static string TextPartners {
            get {
                return ResourceManager.GetString("TextPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string TextPassword {
            get {
                return ResourceManager.GetString("TextPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Change.
        /// </summary>
        public static string TextPasswordChange {
            get {
                return ResourceManager.GetString("TextPasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Password.
        /// </summary>
        public static string TextPasswordRecover {
            get {
                return ResourceManager.GetString("TextPasswordRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery code has been sent to your email.
        /// </summary>
        public static string TextPasswordRecoveryCodeSentOnEmail {
            get {
                return ResourceManager.GetString("TextPasswordRecoveryCodeSentOnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery code has been sent to your phone number.
        /// </summary>
        public static string TextPasswordRecoveryCodeSentOnPhone {
            get {
                return ResourceManager.GetString("TextPasswordRecoveryCodeSentOnPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string TextPasswordReset {
            get {
                return ResourceManager.GetString("TextPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Terms.
        /// </summary>
        public static string TextPaymentTerms {
            get {
                return ResourceManager.GetString("TextPaymentTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string TextPeriod {
            get {
                return ResourceManager.GetString("TextPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Dates.
        /// </summary>
        public static string TextPeriodChoosing {
            get {
                return ResourceManager.GetString("TextPeriodChoosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string TextPhoneNumber {
            get {
                return ResourceManager.GetString("TextPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photogallery.
        /// </summary>
        public static string TextPhotogallery {
            get {
                return ResourceManager.GetString("TextPhotogallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal.
        /// </summary>
        public static string TextPortal {
            get {
                return ResourceManager.GetString("TextPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        public static string TextPremium {
            get {
                return ResourceManager.GetString("TextPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Package.
        /// </summary>
        public static string TextPremiumPackage {
            get {
                return ResourceManager.GetString("TextPremiumPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string TextPrev {
            get {
                return ResourceManager.GetString("TextPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string TextPrice {
            get {
                return ResourceManager.GetString("TextPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If credit.
        /// </summary>
        public static string TextPriceIfCredit {
            get {
                return ResourceManager.GetString("TextPriceIfCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string TextProfile {
            get {
                return ResourceManager.GetString("TextProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit after tax.
        /// </summary>
        public static string TextProfitAfterTax {
            get {
                return ResourceManager.GetString("TextProfitAfterTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit before tax.
        /// </summary>
        public static string TextProfitBeforeTax {
            get {
                return ResourceManager.GetString("TextProfitBeforeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string TextProjects {
            get {
                return ResourceManager.GetString("TextProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter folder name.
        /// </summary>
        public static string TextPromptEnterFolderName {
            get {
                return ResourceManager.GetString("TextPromptEnterFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a page name.
        /// </summary>
        public static string TextPromptEnterPageTitle {
            get {
                return ResourceManager.GetString("TextPromptEnterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Date.
        /// </summary>
        public static string TextPurchaseDate {
            get {
                return ResourceManager.GetString("TextPurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase History.
        /// </summary>
        public static string TextPurchaseHistory {
            get {
                return ResourceManager.GetString("TextPurchaseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Premium Package.
        /// </summary>
        public static string TextPurchasePremiumPackage {
            get {
                return ResourceManager.GetString("TextPurchasePremiumPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To access this information, please purchase the Premium Package.
        /// </summary>
        public static string TextPurchaseToSee {
            get {
                return ResourceManager.GetString("TextPurchaseToSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextReadMore {
            get {
                return ResourceManager.GetString("TextReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string TextRecover {
            get {
                return ResourceManager.GetString("TextRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string TextRegister {
            get {
                return ResourceManager.GetString("TextRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string TextRegistration {
            get {
                return ResourceManager.GetString("TextRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Issue.
        /// </summary>
        public static string TextReleasesDate {
            get {
                return ResourceManager.GetString("TextReleasesDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string TextRepeatPassword {
            get {
                return ResourceManager.GetString("TextRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        public static string TextRevenue {
            get {
                return ResourceManager.GetString("TextRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules and Terms.
        /// </summary>
        public static string TextRulesAndTerms {
            get {
                return ResourceManager.GetString("TextRulesAndTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TextSave {
            get {
                return ResourceManager.GetString("TextSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been saved successfully.
        /// </summary>
        public static string TextSaveSuccess {
            get {
                return ResourceManager.GetString("TextSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string TextSearch {
            get {
                return ResourceManager.GetString("TextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        public static string TextSearchResults {
            get {
                return ResourceManager.GetString("TextSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;info&quot;&gt;Found &lt;span class=&quot;color-blue&quot;&gt;{0}&lt;/span&gt; results ‘&lt;span class=&quot;color-blue&quot;&gt;{1}&lt;/span&gt;’ search phrase&lt;/p&gt;.
        /// </summary>
        public static string TextSearchResultsHaveBeenFound {
            get {
                return ResourceManager.GetString("TextSearchResultsHaveBeenFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Securities.
        /// </summary>
        public static string TextSecuritesQuantity {
            get {
                return ResourceManager.GetString("TextSecuritesQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Securities.
        /// </summary>
        public static string TextSecurities {
            get {
                return ResourceManager.GetString("TextSecurities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Capital.
        /// </summary>
        public static string TextSecuritiesAuthorizedCapital {
            get {
                return ResourceManager.GetString("TextSecuritiesAuthorizedCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Bid/Ask.
        /// </summary>
        public static string TextSecuritiesBestOffers {
            get {
                return ResourceManager.GetString("TextSecuritiesBestOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon.
        /// </summary>
        public static string TextSecuritiesCoupon {
            get {
                return ResourceManager.GetString("TextSecuritiesCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Type.
        /// </summary>
        public static string TextSecuritiesCouponType {
            get {
                return ResourceManager.GetString("TextSecuritiesCouponType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Issue.
        /// </summary>
        public static string TextSecuritiesDateOfIssue {
            get {
                return ResourceManager.GetString("TextSecuritiesDateOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Capitalization.
        /// </summary>
        public static string TextSecuritiesMarketCapitalization {
            get {
                return ResourceManager.GetString("TextSecuritiesMarketCapitalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string TextSecuritiesRaiting {
            get {
                return ResourceManager.GetString("TextSecuritiesRaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Securities Search.
        /// </summary>
        public static string TextSecuritiesSearch {
            get {
                return ResourceManager.GetString("TextSecuritiesSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticker.
        /// </summary>
        public static string TextSecuritiesShortened {
            get {
                return ResourceManager.GetString("TextSecuritiesShortened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocks Outstanding.
        /// </summary>
        public static string TextSecuritiesStocksOutstanding {
            get {
                return ResourceManager.GetString("TextSecuritiesStocksOutstanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string TextSecurityItem {
            get {
                return ResourceManager.GetString("TextSecurityItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Security.
        /// </summary>
        public static string TextSecurityType {
            get {
                return ResourceManager.GetString("TextSecurityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string TextSell {
            get {
                return ResourceManager.GetString("TextSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string TextSend {
            get {
                return ResourceManager.GetString("TextSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send code.
        /// </summary>
        public static string TextSendCode {
            get {
                return ResourceManager.GetString("TextSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string TextSignUp {
            get {
                return ResourceManager.GetString("TextSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and accepted .
        /// </summary>
        public static string TextSignupRulesConfirmation {
            get {
                return ResourceManager.GetString("TextSignupRulesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARCHITECTURE BUREAU.
        /// </summary>
        public static string TextSlogan {
            get {
                return ResourceManager.GetString("TextSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug is not unique.
        /// </summary>
        public static string TextSlugNotUniq {
            get {
                return ResourceManager.GetString("TextSlugNotUniq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug is required.
        /// </summary>
        public static string TextSlugRequired {
            get {
                return ResourceManager.GetString("TextSlugRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string TextSms {
            get {
                return ResourceManager.GetString("TextSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold.
        /// </summary>
        public static string TextSold {
            get {
                return ResourceManager.GetString("TextSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m².
        /// </summary>
        public static string TextSquareMeters {
            get {
                return ResourceManager.GetString("TextSquareMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string TextStandart {
            get {
                return ResourceManager.GetString("TextStandart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string TextStock {
            get {
                return ResourceManager.GetString("TextStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSX Index.
        /// </summary>
        public static string TextStockIndexGSX {
            get {
                return ResourceManager.GetString("TextStockIndexGSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Indices.
        /// </summary>
        public static string TextStockIndices {
            get {
                return ResourceManager.GetString("TextStockIndices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocks.
        /// </summary>
        public static string TextStocks {
            get {
                return ResourceManager.GetString("TextStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string TextSubscribe {
            get {
                return ResourceManager.GetString("TextSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string TextSuccess {
            get {
                return ResourceManager.GetString("TextSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summarize.
        /// </summary>
        public static string TextSummarize {
            get {
                return ResourceManager.GetString("TextSummarize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum number of I/S.
        /// </summary>
        public static string TextSumNumberOfIssuedSecurities {
            get {
                return ResourceManager.GetString("TextSumNumberOfIssuedSecurities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum price.
        /// </summary>
        public static string TextSumPrice {
            get {
                return ResourceManager.GetString("TextSumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrace area.
        /// </summary>
        public static string TextTerraceArea {
            get {
                return ResourceManager.GetString("TextTerraceArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TextText {
            get {
                return ResourceManager.GetString("TextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTC.
        /// </summary>
        public static string TextTradeDealTypeOTC {
            get {
                return ResourceManager.GetString("TextTradeDealTypeOTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Exchange.
        /// </summary>
        public static string TextTradeDealTypeStock {
            get {
                return ResourceManager.GetString("TextTradeDealTypeStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading occurs on business days.
        /// </summary>
        public static string TextTradeHappensEveryday {
            get {
                return ResourceManager.GetString("TextTradeHappensEveryday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trades.
        /// </summary>
        public static string TextTrades {
            get {
                return ResourceManager.GetString("TextTrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Trades.
        /// </summary>
        public static string TextTradesCount {
            get {
                return ResourceManager.GetString("TextTradesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading sessions.
        /// </summary>
        public static string TextTradeSessions {
            get {
                return ResourceManager.GetString("TextTradeSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trades in GEL.
        /// </summary>
        public static string TextTradesInGel {
            get {
                return ResourceManager.GetString("TextTradesInGel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trades in USD.
        /// </summary>
        public static string TextTradesInUsd {
            get {
                return ResourceManager.GetString("TextTradesInUsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Currency.
        /// </summary>
        public static string TextTradingCurrency {
            get {
                return ResourceManager.GetString("TextTradingCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Volume.
        /// </summary>
        public static string TextTradingVolume {
            get {
                return ResourceManager.GetString("TextTradingVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TextType {
            get {
                return ResourceManager.GetString("TextType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond.
        /// </summary>
        public static string TextTypeBond {
            get {
                return ResourceManager.GetString("TextTypeBond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string TextTypeStock {
            get {
                return ResourceManager.GetString("TextTypeStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont send me any emails..
        /// </summary>
        public static string TextUnsubscribeAllEmails {
            get {
                return ResourceManager.GetString("TextUnsubscribeAllEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trades in USD.
        /// </summary>
        public static string TextUsdSession {
            get {
                return ResourceManager.GetString("TextUsdSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trades in USD.
        /// </summary>
        public static string TextUsdSessionHours {
            get {
                return ResourceManager.GetString("TextUsdSessionHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is not unique.
        /// </summary>
        public static string TextUsernameIsNotUniq {
            get {
                return ResourceManager.GetString("TextUsernameIsNotUniq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videogallery.
        /// </summary>
        public static string TextVideoGallery {
            get {
                return ResourceManager.GetString("TextVideoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string TextView {
            get {
                return ResourceManager.GetString("TextView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string TextVolume {
            get {
                return ResourceManager.GetString("TextVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Volume.
        /// </summary>
        public static string TextVolumeOfIssuedSecurities {
            get {
                return ResourceManager.GetString("TextVolumeOfIssuedSecurities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Cost Per Item.
        /// </summary>
        public static string TextVolumePerAverage {
            get {
                return ResourceManager.GetString("TextVolumePerAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string TextWebsite {
            get {
                return ResourceManager.GetString("TextWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Index.
        /// </summary>
        public static string TextWithSectorIndex {
            get {
                return ResourceManager.GetString("TextWithSectorIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string TextYear {
            get {
                return ResourceManager.GetString("TextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string TextYes {
            get {
                return ResourceManager.GetString("TextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გაითვალისწინეთ, რომ ფასიანი subscription-ის ყიდვა არის შესძლებელი მოგვიანებითაც..
        /// </summary>
        public static string TextYouCanBuySubsriptionLater {
            get {
                return ResourceManager.GetString("TextYouCanBuySubsriptionLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have an account?.
        /// </summary>
        public static string TextYouDonotHaveAccount {
            get {
                return ResourceManager.GetString("TextYouDonotHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token is expired.
        /// </summary>
        public static string ValidationAccessTokenExpired {
            get {
                return ResourceManager.GetString("ValidationAccessTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token is invalid.
        /// </summary>
        public static string ValidationAccessTokenInvalid {
            get {
                return ResourceManager.GetString("ValidationAccessTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not activated.
        /// </summary>
        public static string ValidationAccountIsNotActivated {
            get {
                return ResourceManager.GetString("ValidationAccountIsNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete building, because it has floors.
        /// </summary>
        public static string ValidationBuildingHasFloor {
            get {
                return ResourceManager.GetString("ValidationBuildingHasFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha is required.
        /// </summary>
        public static string ValidationCaptchaRequired {
            get {
                return ResourceManager.GetString("ValidationCaptchaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is invalid.
        /// </summary>
        public static string ValidationConfirmationCodeInvalid {
            get {
                return ResourceManager.GetString("ValidationConfirmationCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string ValidationConfirmationCodeRequired {
            get {
                return ResourceManager.GetString("ValidationConfirmationCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum interval between start and end date must be 90 days.
        /// </summary>
        public static string ValidationDatesInterval {
            get {
                return ResourceManager.GetString("ValidationDatesInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string ValidationEmailIsRequired {
            get {
                return ResourceManager.GetString("ValidationEmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not found.
        /// </summary>
        public static string ValidationEmailNotFound {
            get {
                return ResourceManager.GetString("ValidationEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not unique.
        /// </summary>
        public static string ValidationEmailNotUnique {
            get {
                return ResourceManager.GetString("ValidationEmailNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        public static string ValidationEmailNotValid {
            get {
                return ResourceManager.GetString("ValidationEmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname required.
        /// </summary>
        public static string ValidationFirstnameRequired {
            get {
                return ResourceManager.GetString("ValidationFirstnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete floor, because it has flats.
        /// </summary>
        public static string ValidationFloorHasFlats {
            get {
                return ResourceManager.GetString("ValidationFloorHasFlats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not accept the terms and rules.
        /// </summary>
        public static string ValidationHasNotAcceptedTheRules {
            get {
                return ResourceManager.GetString("ValidationHasNotAcceptedTheRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string ValidationInvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("ValidationInvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname required.
        /// </summary>
        public static string ValidationLastnameRequired {
            get {
                return ResourceManager.GetString("ValidationLastnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link is required.
        /// </summary>
        public static string ValidationLinkRequired {
            get {
                return ResourceManager.GetString("ValidationLinkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number required.
        /// </summary>
        public static string ValidationMobileNumberRequired {
            get {
                return ResourceManager.GetString("ValidationMobileNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is not correct.
        /// </summary>
        public static string ValidationOldPasswordNotMatch {
            get {
                return ResourceManager.GetString("ValidationOldPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is required.
        /// </summary>
        public static string ValidationOldPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationOldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has to be alphanumeric (a-z, A-Z, 0-9).
        /// </summary>
        public static string ValidationPasswordAlphanumeric {
            get {
                return ResourceManager.GetString("ValidationPasswordAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length has to be min 8 symbols.
        /// </summary>
        public static string ValidationPasswordLength {
            get {
                return ResourceManager.GetString("ValidationPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has to contain at least one digit.
        /// </summary>
        public static string ValidationPasswordMinOneDigit {
            get {
                return ResourceManager.GetString("ValidationPasswordMinOneDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has to contain at least one letter.
        /// </summary>
        public static string ValidationPasswordMinOneLetter {
            get {
                return ResourceManager.GetString("ValidationPasswordMinOneLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required.
        /// </summary>
        public static string ValidationPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string ValidationPasswordsNotMatch {
            get {
                return ResourceManager.GetString("ValidationPasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number not found.
        /// </summary>
        public static string ValidationPhoneNumberNotFound {
            get {
                return ResourceManager.GetString("ValidationPhoneNumberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete project, because it has buildings.
        /// </summary>
        public static string ValidationProjectHasBuildings {
            get {
                return ResourceManager.GetString("ValidationProjectHasBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password required.
        /// </summary>
        public static string ValidationRepeatPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationRepeatPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is required.
        /// </summary>
        public static string ValidationRequiredField {
            get {
                return ResourceManager.GetString("ValidationRequiredField", resourceCulture);
            }
        }
    }
}
