#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ECommerceTest")]
	public partial class DBCoreDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBCoreDataContext() : 
				base(global::Core.Properties.Settings.Default.ECommerceTestConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBCoreDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCoreDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCoreDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCoreDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DictionariesIUD")]
		public int DictionariesIUD([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DatabaseAction", DbType="TinyInt")] System.Nullable<byte> databaseAction, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DictionaryID", DbType="Int")] ref System.Nullable<int> dictionaryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Caption", DbType="NVarChar(200)")] string caption, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CaptionEng", DbType="NVarChar(200)")] string captionEng, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CaptionRus", DbType="NVarChar(200)")] string captionRus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentID", DbType="Int")] System.Nullable<int> parentID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StringCode", DbType="NVarChar(100)")] string stringCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IntCode", DbType="Int")] System.Nullable<int> intCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DecimalValue", DbType="Money")] System.Nullable<decimal> decimalValue, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DictionaryCode", DbType="SmallInt")] System.Nullable<short> dictionaryCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsDefault", DbType="Bit")] System.Nullable<bool> isDefault, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsVisible", DbType="Bit")] System.Nullable<bool> isVisible, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortIndex", DbType="Int")] System.Nullable<int> sortIndex)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), databaseAction, dictionaryID, caption, captionEng, captionRus, parentID, stringCode, intCode, decimalValue, dictionaryCode, isDefault, isVisible, sortIndex);
			dictionaryID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PermissionsIUD")]
		public int PermissionsIUD([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DatabaseAction", DbType="TinyInt")] System.Nullable<byte> databaseAction, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermissionID", DbType="Int")] ref System.Nullable<int> permissionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentID", DbType="Int")] System.Nullable<int> parentID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Caption", DbType="NVarChar(100)")] string caption, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PagePath", DbType="NVarChar(100)")] string pagePath, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodeName", DbType="NVarChar(100)")] string codeName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermissionCode", DbType="VarChar(100)")] string permissionCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsMenuItem", DbType="Bit")] System.Nullable<bool> isMenuItem, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MenuIcon", DbType="NVarChar(50)")] string menuIcon, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortIndex", DbType="Int")] System.Nullable<int> sortIndex)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), databaseAction, permissionID, parentID, caption, pagePath, codeName, permissionCode, isMenuItem, menuIcon, sortIndex);
			permissionID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DictionariesList", IsComposable=true)]
		public IQueryable<DictionariesListResult> DictionariesList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Level", DbType="Int")] System.Nullable<int> level, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DictionaryCode", DbType="Int")] System.Nullable<int> dictionaryCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsVisible", DbType="Bit")] System.Nullable<bool> isVisible)
		{
			return this.CreateMethodCallQuery<DictionariesListResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), level, dictionaryCode, isVisible);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PermissionsList", IsComposable=true)]
		public IQueryable<PermissionsListResult> PermissionsList()
		{
			return this.CreateMethodCallQuery<PermissionsListResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UsersIsEmailUnique", IsComposable=true)]
		public System.Nullable<bool> UsersIsEmailUnique([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] System.Nullable<int> userID)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, userID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UsersGetSingleUserByEmailAndPassword", IsComposable=true)]
		public System.Xml.Linq.XElement UsersGetSingleUserByEmailAndPassword([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(500)")] string password)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, password).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FaqSyncSortIndexes")]
		public int FaqSyncSortIndexes([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortIndexesXml", DbType="Xml")] System.Xml.Linq.XElement sortIndexesXml)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sortIndexesXml);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CarouselSyncSortIndexes")]
		public int CarouselSyncSortIndexes([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortIndexesXml", DbType="Xml")] System.Xml.Linq.XElement sortIndexesXml)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sortIndexesXml);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CarouselGetSingleItemByID", IsComposable=true)]
		public System.Xml.Linq.XElement CarouselGetSingleItemByID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarouselID", DbType="Int")] System.Nullable<int> carouselID)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), carouselID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FacebookGalleriesSyncSortIndexes")]
		public int FacebookGalleriesSyncSortIndexes([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortIndexesXml", DbType="Xml")] System.Xml.Linq.XElement sortIndexesXml)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sortIndexesXml);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FacebookGalleriesIUD")]
		public int FacebookGalleriesIUD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GalleryID", DbType="Int")] ref System.Nullable<int> galleryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FacebookGalleryID", DbType="VarChar(20)")] string facebookGalleryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GalleryCaption", DbType="NVarChar(200)")] string galleryCaption, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GalleryCaptionEng", DbType="NVarChar(200)")] string galleryCaptionEng, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GalleryCaptionRus", DbType="NVarChar(200)")] string galleryCaptionRus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GalleryDescription", DbType="NVarChar(MAX)")] string galleryDescription, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GalleryDescriptionEng", DbType="NVarChar(MAX)")] string galleryDescriptionEng, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GalleryDescriptionRus", DbType="NVarChar(MAX)")] string galleryDescriptionRus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPublished", DbType="Bit")] System.Nullable<bool> isPublished)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, galleryID, facebookGalleryID, galleryCaption, galleryCaptionEng, galleryCaptionRus, galleryDescription, galleryDescriptionEng, galleryDescriptionRus, isPublished);
			galleryID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FacebookGalleriesList", IsComposable=true)]
		public IQueryable<FacebookGalleriesListResult> FacebookGalleriesList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPublished", DbType="Bit")] System.Nullable<bool> isPublished)
		{
			return this.CreateMethodCallQuery<FacebookGalleriesListResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), isPublished);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FacebookGalleriesIsGalleryIDUniq", IsComposable=true)]
		public System.Nullable<bool> FacebookGalleriesIsGalleryIDUniq([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FacebookGalleryID", DbType="VarChar(20)")] string facebookGalleryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GalleryID", DbType="Int")] System.Nullable<int> galleryID)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), facebookGalleryID, galleryID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FacebookGalleryGetSingleByID", IsComposable=true)]
		public System.Xml.Linq.XElement FacebookGalleryGetSingleByID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GalleryID", DbType="Int")] System.Nullable<int> galleryID)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), galleryID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CategoriesGetSingleByID", IsComposable=true)]
		public System.Xml.Linq.XElement CategoriesGetSingleByID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryID", DbType="Int")] System.Nullable<int> categoryID)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categoryID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CategoriesGetSingleBySlug", IsComposable=true)]
		public System.Xml.Linq.XElement CategoriesGetSingleBySlug([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategorySlug", DbType="NVarChar(200)")] string categorySlug)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categorySlug).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CategoriesIsSlugUniq", IsComposable=true)]
		public System.Nullable<bool> CategoriesIsSlugUniq([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Slug", DbType="NVarChar(100)")] string slug, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryID", DbType="Int")] System.Nullable<int> categoryID)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), slug, categoryID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProductsGetSingleBySlug", IsComposable=true)]
		public System.Xml.Linq.XElement ProductsGetSingleBySlug([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductSulg", DbType="NVarChar(100)")] string productSulg)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productSulg).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProductsIsSlugUniq", IsComposable=true)]
		public System.Nullable<bool> ProductsIsSlugUniq([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Slug", DbType="NVarChar(100)")] string slug, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductID", DbType="Int")] System.Nullable<int> productID)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), slug, productID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProductsGetSingleByID", IsComposable=true)]
		public System.Xml.Linq.XElement ProductsGetSingleByID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductID", DbType="Int")] System.Nullable<int> productID)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UsersGetSingleUserByUserID", IsComposable=true)]
		public System.Xml.Linq.XElement UsersGetSingleUserByUserID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] System.Nullable<int> userID)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.OrderDetailsIUD")]
		public int OrderDetailsIUD([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DatabaseAction", DbType="TinyInt")] System.Nullable<byte> databaseAction, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderDetailID", DbType="Int")] System.Nullable<int> orderDetailID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductCount", DbType="Int")] ref System.Nullable<int> productCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), databaseAction, orderDetailID, productCount);
			productCount = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.OrdersGetSingleByID", IsComposable=true)]
		public System.Xml.Linq.XElement OrdersGetSingleByID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UsersGetSingleByEmail", IsComposable=true)]
		public System.Xml.Linq.XElement UsersGetSingleByEmail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(200)")] string email)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NotificationManager_GetAccountActivationEmailBodyText", IsComposable=true)]
		public string NotificationManager_GetAccountActivationEmailBodyText([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Firstname", DbType="NVarChar(50)")] string firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApplicationAddress", DbType="NVarChar(200)")] string applicationAddress)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), firstname, applicationAddress).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NotificationManager_GetAccountDeactivationEmailBodyText", IsComposable=true)]
		public string NotificationManager_GetAccountDeactivationEmailBodyText([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Firstname", DbType="NVarChar(50)")] string firstname)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), firstname).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NotificationManager_GetPasswordRecoveryEmailBodyText", IsComposable=true)]
		public string NotificationManager_GetPasswordRecoveryEmailBodyText([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ConfirmationCode", DbType="VarChar(20)")] string confirmationCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Firstname", DbType="NVarChar(50)")] string firstname)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), confirmationCode, firstname).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NotificationManager_GetContactFormEmailBodyText", IsComposable=true)]
		public string NotificationManager_GetContactFormEmailBodyText([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Firstname", DbType="NVarChar(50)")] string firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="NVarChar(50)")] string lastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Phone", DbType="NVarChar(50)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CountryID", DbType="Int")] System.Nullable<int> countryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StateID", DbType="Int")] System.Nullable<int> stateID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="NVarChar(100)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsProfessional", DbType="Bit")] System.Nullable<bool> isProfessional, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TopicID", DbType="Int")] System.Nullable<int> topicID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="NVarChar(MAX)")] string message)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), firstname, lastName, email, phone, countryID, stateID, city, isProfessional, topicID, message).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CategoriesSyncParentsAndSortIndexes")]
		public int CategoriesSyncParentsAndSortIndexes([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentsAndSortIndexesXml", DbType="Xml")] System.Xml.Linq.XElement parentsAndSortIndexesXml)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parentsAndSortIndexesXml);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NotificationManager_GetConfirmationCodeEmailBodyText", IsComposable=true)]
		public string NotificationManager_GetConfirmationCodeEmailBodyText([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Firstname", DbType="NVarChar(50)")] string firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ConfirmationCode", DbType="VarChar(20)")] string confirmationCode)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), firstname, confirmationCode).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.OrdersGetSingleOrderWithStatusBasketByCustomerID", IsComposable=true)]
		public System.Xml.Linq.XElement OrdersGetSingleOrderWithStatusBasketByCustomerID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customerID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PaypalTransactionsIUD")]
		public int PaypalTransactionsIUD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TransactionID", DbType="Int")] ref System.Nullable<int> transactionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TransactionTypeID", DbType="Int")] System.Nullable<int> transactionTypeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TransactionTypeCode", DbType="Int")] System.Nullable<int> transactionTypeCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestUrl", DbType="NVarChar(500)")] string requestUrl, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestParameters", DbType="NVarChar(MAX)")] string requestParameters, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResponseString", DbType="NVarChar(MAX)")] string responseString, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, transactionID, transactionTypeID, transactionTypeCode, requestUrl, requestParameters, responseString, orderID);
			transactionID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ADNTransactionsIUD")]
		public int ADNTransactionsIUD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecordID", DbType="Int")] ref System.Nullable<int> recordID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ADNTransactionID", DbType="VarChar(20)")] string aDNTransactionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestStr", DbType="NVarChar(MAX)")] string requestStr, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResponseStr", DbType="NVarChar(MAX)")] string responseStr, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, recordID, aDNTransactionID, requestStr, responseStr, orderID);
			recordID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NotificationManager_GetSaleNotificationEmailBodyText", IsComposable=true)]
		public string NotificationManager_GetSaleNotificationEmailBodyText([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DictionaryGetDictionaryIDByDictionaryCodeAndIntCode", IsComposable=true)]
		public System.Nullable<int> DictionaryGetDictionaryIDByDictionaryCodeAndIntCode([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DictionaryCode", DbType="Int")] System.Nullable<int> dictionaryCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IntCode", DbType="Int")] System.Nullable<int> intCode)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dictionaryCode, intCode).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DictionariesGetStringCodes", IsComposable=true)]
		public System.Xml.Linq.XElement DictionariesGetStringCodes([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShippingCountryID", DbType="Int")] System.Nullable<int> shippingCountryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShippingRegion", DbType="NVarChar(50)")] string shippingRegion)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), shippingCountryID, shippingRegion).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DictionaryGetDictionarySettingsStrigCodeByIntCode", IsComposable=true)]
		public string DictionaryGetDictionarySettingsStrigCodeByIntCode([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IntCode", DbType="Int")] System.Nullable<int> intCode)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intCode).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NotificationManager_GetPaymentSuccessEmailBodyText", IsComposable=true)]
		public string NotificationManager_GetPaymentSuccessEmailBodyText([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.OrderDetailsSyncProductCount")]
		public int OrderDetailsSyncProductCount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductCountXml", DbType="Xml")] System.Xml.Linq.XElement productCountXml)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customerID, productCountXml);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PermissionsDeleteRecursive")]
		public int PermissionsDeleteRecursive([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermissionID", DbType="Int")] System.Nullable<int> permissionID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), permissionID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FaqIUD")]
		public int FaqIUD([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DatabaseAction", DbType="TinyInt")] System.Nullable<byte> databaseAction, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FaqID", DbType="Int")] ref System.Nullable<int> faqID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Question", DbType="NVarChar(MAX)")] string question, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Answer", DbType="NVarChar(MAX)")] string answer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortIndex", DbType="Int")] System.Nullable<int> sortIndex, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPublished", DbType="Bit")] System.Nullable<bool> isPublished)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), databaseAction, faqID, question, answer, sortIndex, isPublished);
			faqID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FaqList", IsComposable=true)]
		public IQueryable<FaqListResult> FaqList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPublished", DbType="Bit")] System.Nullable<bool> isPublished)
		{
			return this.CreateMethodCallQuery<FaqListResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), isPublished);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CategoriesIUD")]
		public int CategoriesIUD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryID", DbType="Int")] ref System.Nullable<int> categoryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryTheme", DbType="Int")] System.Nullable<int> categoryTheme, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryCaption", DbType="NVarChar(200)")] string categoryCaption, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryDescription", DbType="NVarChar(MAX)")] string categoryDescription, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryImageFilename", DbType="NVarChar(200)")] string categoryImageFilename, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategorySlug", DbType="NVarChar(500)")] string categorySlug, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPublished", DbType="Bit")] System.Nullable<bool> isPublished)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, categoryID, categoryTheme, categoryCaption, categoryDescription, categoryImageFilename, categorySlug, isPublished);
			categoryID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CarouselIUD")]
		public int CarouselIUD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarouselID", DbType="Int")] ref System.Nullable<int> carouselID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarouselCaption", DbType="NVarChar(200)")] string carouselCaption, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarouselText", DbType="NVarChar(MAX)")] string carouselText, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarouselUrl", DbType="NVarChar(200)")] string carouselUrl, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarouselImageFilename", DbType="NVarChar(200)")] string carouselImageFilename, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPublished", DbType="Bit")] System.Nullable<bool> isPublished)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, carouselID, carouselCaption, carouselText, carouselUrl, carouselImageFilename, isPublished);
			carouselID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CarouselList", IsComposable=true)]
		public IQueryable<CarouselListResult> CarouselList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPublished", DbType="Bit")] System.Nullable<bool> isPublished)
		{
			return this.CreateMethodCallQuery<CarouselListResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), isPublished);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CategoriesList", IsComposable=true)]
		public IQueryable<CategoriesListResult> CategoriesList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPublished", DbType="Bit")] System.Nullable<bool> isPublished)
		{
			return this.CreateMethodCallQuery<CategoriesListResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), isPublished);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProductsList", IsComposable=true)]
		public IQueryable<ProductsListResult> ProductsList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPublished", DbType="Bit")] System.Nullable<bool> isPublished, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategorySlug", DbType="NVarChar(200)")] string categorySlug)
		{
			return this.CreateMethodCallQuery<ProductsListResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), isPublished, categorySlug);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProductsIUD")]
		public int ProductsIUD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductID", DbType="Int")] ref System.Nullable<int> productID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductSlug", DbType="NVarChar(200)")] string productSlug, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryID", DbType="Int")] System.Nullable<int> categoryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductCaption", DbType="NVarChar(200)")] string productCaption, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductPrice", DbType="Money")] System.Nullable<decimal> productPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductOldPrice", DbType="Money")] System.Nullable<decimal> productOldPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductDescription", DbType="NVarChar(MAX)")] string productDescription, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductImageFilename", DbType="NVarChar(200)")] string productImageFilename, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPublished", DbType="Bit")] System.Nullable<bool> isPublished)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, productID, productSlug, categoryID, productCaption, productPrice, productOldPrice, productDescription, productImageFilename, isPublished);
			productID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UsersDelete")]
		public int UsersDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] System.Nullable<int> userID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UsersIUD")]
		public int UsersIUD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] ref System.Nullable<int> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(200)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(500)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Firstname", DbType="NVarChar(50)")] string firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lastname", DbType="NVarChar(50)")] string lastname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Birthdate", DbType="Date")] System.Nullable<System.DateTime> birthdate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="VarChar(20)")] string mobile, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Avatar", DbType="NVarChar(100)")] string avatar, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, userID, email, password, firstname, lastname, birthdate, mobile, avatar, isActive);
			userID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UsersList", IsComposable=true)]
		public IQueryable<UsersListResult> UsersList()
		{
			return this.CreateMethodCallQuery<UsersListResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.OrderDetailsList", IsComposable=true)]
		public IQueryable<OrderDetailsListResult> OrderDetailsList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID)
		{
			return this.CreateMethodCallQuery<OrderDetailsListResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customerID, orderID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.OrderDetailsInsert")]
		public int OrderDetailsInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] ref System.Nullable<int> orderID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductID", DbType="Int")] System.Nullable<int> productID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductCount", DbType="Int")] ref System.Nullable<int> productCount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductPrice", DbType="Money")] System.Nullable<decimal> productPrice)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID, customerID, productID, productCount, productPrice);
			orderID = ((System.Nullable<int>)(result.GetParameterValue(0)));
			productCount = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProductsListFiltered", IsComposable=true)]
		public IQueryable<ProductsListFilteredResult> ProductsListFiltered([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategorySlug", DbType="NVarChar(200)")] string categorySlug, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNumber", DbType="Int")] System.Nullable<int> pageNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemsPerPage", DbType="Int")] System.Nullable<int> itemsPerPage)
		{
			return this.CreateMethodCallQuery<ProductsListFilteredResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categorySlug, pageNumber, itemsPerPage);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.OrdersUpdate")]
		public int OrdersUpdate(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] ref System.Nullable<int> orderID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderStatusID", DbType="Int")] System.Nullable<int> orderStatusID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShippingFirstname", DbType="NVarChar(100)")] string shippingFirstname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShippingLastname", DbType="NVarChar(100)")] string shippingLastname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShippingAddress1", DbType="NVarChar(100)")] string shippingAddress1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShippingAddress2", DbType="NVarChar(100)")] string shippingAddress2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShippingCity", DbType="NVarChar(50)")] string shippingCity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShippingRegion", DbType="NVarChar(50)")] string shippingRegion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShippingCountryID", DbType="Int")] System.Nullable<int> shippingCountryID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShippingZip", DbType="NVarChar(50)")] string shippingZip, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsBillingSameAsShipping", DbType="Bit")] System.Nullable<bool> isBillingSameAsShipping, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingFirstname", DbType="NVarChar(100)")] string billingFirstname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingLastname", DbType="NVarChar(100)")] string billingLastname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingAddress1", DbType="NVarChar(100)")] string billingAddress1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingAddress2", DbType="NVarChar(100)")] string billingAddress2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingCity", DbType="NVarChar(50)")] string billingCity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingRegion", DbType="NVarChar(50)")] string billingRegion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingCountryID", DbType="Int")] System.Nullable<int> billingCountryID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingZip", DbType="NVarChar(50)")] string billingZip, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Phone", DbType="VarChar(50)")] string phone, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderPaymentDateTime", DbType="DateTime")] System.Nullable<System.DateTime> orderPaymentDateTime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsOrderDelivered", DbType="Bit")] System.Nullable<bool> isOrderDelivered, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentOptionID", DbType="Int")] System.Nullable<int> paymentOptionID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TransactionID", DbType="NVarChar(500)")] string transactionID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID, orderStatusID, shippingFirstname, shippingLastname, shippingAddress1, shippingAddress2, shippingCity, shippingRegion, shippingCountryID, shippingZip, isBillingSameAsShipping, billingFirstname, billingLastname, billingAddress1, billingAddress2, billingCity, billingRegion, billingCountryID, billingZip, phone, orderPaymentDateTime, isOrderDelivered, paymentOptionID, transactionID);
			orderID = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.OrdersList", IsComposable=true)]
		public IQueryable<OrdersListResult> OrdersList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderStatusIntCode", DbType="Int")] System.Nullable<int> orderStatusIntCode)
		{
			return this.CreateMethodCallQuery<OrdersListResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customerID, orderStatusIntCode);
		}
	}
	
	public partial class DictionariesListResult
	{
		
		private int _DictionaryID;
		
		private string _Caption;
		
		private string _CaptionEng;
		
		private string _CaptionRus;
		
		private System.Nullable<int> _ParentID;
		
		private string _StringCode;
		
		private System.Nullable<int> _IntCode;
		
		private System.Nullable<decimal> _DecimalValue;
		
		private short _DictionaryCode;
		
		private bool _IsDefault;
		
		private bool _IsVisible;
		
		private System.Nullable<int> _SortIndex;
		
		public DictionariesListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DictionaryID", DbType="Int NOT NULL")]
		public int DictionaryID
		{
			get
			{
				return this._DictionaryID;
			}
			set
			{
				if ((this._DictionaryID != value))
				{
					this._DictionaryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(200)")]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this._Caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaptionEng", DbType="NVarChar(200)")]
		public string CaptionEng
		{
			get
			{
				return this._CaptionEng;
			}
			set
			{
				if ((this._CaptionEng != value))
				{
					this._CaptionEng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaptionRus", DbType="NVarChar(200)")]
		public string CaptionRus
		{
			get
			{
				return this._CaptionRus;
			}
			set
			{
				if ((this._CaptionRus != value))
				{
					this._CaptionRus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int")]
		public System.Nullable<int> ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StringCode", DbType="NVarChar(100)")]
		public string StringCode
		{
			get
			{
				return this._StringCode;
			}
			set
			{
				if ((this._StringCode != value))
				{
					this._StringCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntCode", DbType="Int")]
		public System.Nullable<int> IntCode
		{
			get
			{
				return this._IntCode;
			}
			set
			{
				if ((this._IntCode != value))
				{
					this._IntCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DecimalValue", DbType="Money")]
		public System.Nullable<decimal> DecimalValue
		{
			get
			{
				return this._DecimalValue;
			}
			set
			{
				if ((this._DecimalValue != value))
				{
					this._DecimalValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DictionaryCode", DbType="SmallInt NOT NULL")]
		public short DictionaryCode
		{
			get
			{
				return this._DictionaryCode;
			}
			set
			{
				if ((this._DictionaryCode != value))
				{
					this._DictionaryCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDefault", DbType="Bit NOT NULL")]
		public bool IsDefault
		{
			get
			{
				return this._IsDefault;
			}
			set
			{
				if ((this._IsDefault != value))
				{
					this._IsDefault = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVisible", DbType="Bit NOT NULL")]
		public bool IsVisible
		{
			get
			{
				return this._IsVisible;
			}
			set
			{
				if ((this._IsVisible != value))
				{
					this._IsVisible = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortIndex", DbType="Int")]
		public System.Nullable<int> SortIndex
		{
			get
			{
				return this._SortIndex;
			}
			set
			{
				if ((this._SortIndex != value))
				{
					this._SortIndex = value;
				}
			}
		}
	}
	
	public partial class PermissionsListResult
	{
		
		private int _PermissionID;
		
		private System.Nullable<int> _ParentID;
		
		private string _Caption;
		
		private string _PagePath;
		
		private string _CodeName;
		
		private string _PermissionCode;
		
		private bool _IsMenuItem;
		
		private string _MenuIcon;
		
		private System.Nullable<int> _SortIndex;
		
		private System.DateTime _CRTime;
		
		public PermissionsListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermissionID", DbType="Int NOT NULL")]
		public int PermissionID
		{
			get
			{
				return this._PermissionID;
			}
			set
			{
				if ((this._PermissionID != value))
				{
					this._PermissionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int")]
		public System.Nullable<int> ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(100)")]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this._Caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PagePath", DbType="NVarChar(100)")]
		public string PagePath
		{
			get
			{
				return this._PagePath;
			}
			set
			{
				if ((this._PagePath != value))
				{
					this._PagePath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeName", DbType="NVarChar(100)")]
		public string CodeName
		{
			get
			{
				return this._CodeName;
			}
			set
			{
				if ((this._CodeName != value))
				{
					this._CodeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermissionCode", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string PermissionCode
		{
			get
			{
				return this._PermissionCode;
			}
			set
			{
				if ((this._PermissionCode != value))
				{
					this._PermissionCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMenuItem", DbType="Bit NOT NULL")]
		public bool IsMenuItem
		{
			get
			{
				return this._IsMenuItem;
			}
			set
			{
				if ((this._IsMenuItem != value))
				{
					this._IsMenuItem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuIcon", DbType="NVarChar(50)")]
		public string MenuIcon
		{
			get
			{
				return this._MenuIcon;
			}
			set
			{
				if ((this._MenuIcon != value))
				{
					this._MenuIcon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortIndex", DbType="Int")]
		public System.Nullable<int> SortIndex
		{
			get
			{
				return this._SortIndex;
			}
			set
			{
				if ((this._SortIndex != value))
				{
					this._SortIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
	}
	
	public partial class FacebookGalleriesListResult
	{
		
		private int _GalleryID;
		
		private string _FacebookGalleryID;
		
		private string _GalleryCaption;
		
		private string _GalleryCaptionEng;
		
		private string _GalleryCaptionRus;
		
		private string _GalleryDescription;
		
		private string _GalleryDescriptionEng;
		
		private string _GalleryDescriptionRus;
		
		private bool _IsPublished;
		
		private System.Nullable<int> _SortIndex;
		
		private System.DateTime _CRTime;
		
		public FacebookGalleriesListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GalleryID", DbType="Int NOT NULL")]
		public int GalleryID
		{
			get
			{
				return this._GalleryID;
			}
			set
			{
				if ((this._GalleryID != value))
				{
					this._GalleryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacebookGalleryID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string FacebookGalleryID
		{
			get
			{
				return this._FacebookGalleryID;
			}
			set
			{
				if ((this._FacebookGalleryID != value))
				{
					this._FacebookGalleryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GalleryCaption", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string GalleryCaption
		{
			get
			{
				return this._GalleryCaption;
			}
			set
			{
				if ((this._GalleryCaption != value))
				{
					this._GalleryCaption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GalleryCaptionEng", DbType="NVarChar(200)")]
		public string GalleryCaptionEng
		{
			get
			{
				return this._GalleryCaptionEng;
			}
			set
			{
				if ((this._GalleryCaptionEng != value))
				{
					this._GalleryCaptionEng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GalleryCaptionRus", DbType="NVarChar(200)")]
		public string GalleryCaptionRus
		{
			get
			{
				return this._GalleryCaptionRus;
			}
			set
			{
				if ((this._GalleryCaptionRus != value))
				{
					this._GalleryCaptionRus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GalleryDescription", DbType="NVarChar(MAX)")]
		public string GalleryDescription
		{
			get
			{
				return this._GalleryDescription;
			}
			set
			{
				if ((this._GalleryDescription != value))
				{
					this._GalleryDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GalleryDescriptionEng", DbType="NVarChar(MAX)")]
		public string GalleryDescriptionEng
		{
			get
			{
				return this._GalleryDescriptionEng;
			}
			set
			{
				if ((this._GalleryDescriptionEng != value))
				{
					this._GalleryDescriptionEng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GalleryDescriptionRus", DbType="NVarChar(MAX)")]
		public string GalleryDescriptionRus
		{
			get
			{
				return this._GalleryDescriptionRus;
			}
			set
			{
				if ((this._GalleryDescriptionRus != value))
				{
					this._GalleryDescriptionRus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPublished", DbType="Bit NOT NULL")]
		public bool IsPublished
		{
			get
			{
				return this._IsPublished;
			}
			set
			{
				if ((this._IsPublished != value))
				{
					this._IsPublished = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortIndex", DbType="Int")]
		public System.Nullable<int> SortIndex
		{
			get
			{
				return this._SortIndex;
			}
			set
			{
				if ((this._SortIndex != value))
				{
					this._SortIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
	}
	
	public partial class FaqListResult
	{
		
		private int _FaqID;
		
		private string _Question;
		
		private string _Answer;
		
		private System.Nullable<int> _SortIndex;
		
		private bool _IsPublished;
		
		private System.DateTime _CRTime;
		
		public FaqListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaqID", DbType="Int NOT NULL")]
		public int FaqID
		{
			get
			{
				return this._FaqID;
			}
			set
			{
				if ((this._FaqID != value))
				{
					this._FaqID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="NVarChar(MAX)")]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this._Question = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer", DbType="NVarChar(MAX)")]
		public string Answer
		{
			get
			{
				return this._Answer;
			}
			set
			{
				if ((this._Answer != value))
				{
					this._Answer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortIndex", DbType="Int")]
		public System.Nullable<int> SortIndex
		{
			get
			{
				return this._SortIndex;
			}
			set
			{
				if ((this._SortIndex != value))
				{
					this._SortIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPublished", DbType="Bit NOT NULL")]
		public bool IsPublished
		{
			get
			{
				return this._IsPublished;
			}
			set
			{
				if ((this._IsPublished != value))
				{
					this._IsPublished = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
	}
	
	public partial class CarouselListResult
	{
		
		private int _CarouselID;
		
		private string _CarouselCaption;
		
		private string _CarouselText;
		
		private string _CarouselUrl;
		
		private string _CarouselImageFilename;
		
		private System.Nullable<int> _SortIndex;
		
		private bool _IsPublished;
		
		private System.DateTime _CRTime;
		
		public CarouselListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarouselID", DbType="Int NOT NULL")]
		public int CarouselID
		{
			get
			{
				return this._CarouselID;
			}
			set
			{
				if ((this._CarouselID != value))
				{
					this._CarouselID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarouselCaption", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string CarouselCaption
		{
			get
			{
				return this._CarouselCaption;
			}
			set
			{
				if ((this._CarouselCaption != value))
				{
					this._CarouselCaption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarouselText", DbType="NVarChar(MAX)")]
		public string CarouselText
		{
			get
			{
				return this._CarouselText;
			}
			set
			{
				if ((this._CarouselText != value))
				{
					this._CarouselText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarouselUrl", DbType="NVarChar(200)")]
		public string CarouselUrl
		{
			get
			{
				return this._CarouselUrl;
			}
			set
			{
				if ((this._CarouselUrl != value))
				{
					this._CarouselUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarouselImageFilename", DbType="NVarChar(200)")]
		public string CarouselImageFilename
		{
			get
			{
				return this._CarouselImageFilename;
			}
			set
			{
				if ((this._CarouselImageFilename != value))
				{
					this._CarouselImageFilename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortIndex", DbType="Int")]
		public System.Nullable<int> SortIndex
		{
			get
			{
				return this._SortIndex;
			}
			set
			{
				if ((this._SortIndex != value))
				{
					this._SortIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPublished", DbType="Bit NOT NULL")]
		public bool IsPublished
		{
			get
			{
				return this._IsPublished;
			}
			set
			{
				if ((this._IsPublished != value))
				{
					this._IsPublished = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
	}
	
	public partial class CategoriesListResult
	{
		
		private int _CategoryID;
		
		private System.Nullable<int> _CategoryTheme;
		
		private string _CategoryCaption;
		
		private string _CategorySlug;
		
		private string _CategoryDescription;
		
		private string _CategoryImageFilename;
		
		private bool _IsPublished;
		
		private System.Nullable<int> _SortIndex;
		
		public CategoriesListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID", DbType="Int NOT NULL")]
		public int CategoryID
		{
			get
			{
				return this._CategoryID;
			}
			set
			{
				if ((this._CategoryID != value))
				{
					this._CategoryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryTheme", DbType="Int")]
		public System.Nullable<int> CategoryTheme
		{
			get
			{
				return this._CategoryTheme;
			}
			set
			{
				if ((this._CategoryTheme != value))
				{
					this._CategoryTheme = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryCaption", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string CategoryCaption
		{
			get
			{
				return this._CategoryCaption;
			}
			set
			{
				if ((this._CategoryCaption != value))
				{
					this._CategoryCaption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategorySlug", DbType="NVarChar(200)")]
		public string CategorySlug
		{
			get
			{
				return this._CategorySlug;
			}
			set
			{
				if ((this._CategorySlug != value))
				{
					this._CategorySlug = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryDescription", DbType="NVarChar(MAX)")]
		public string CategoryDescription
		{
			get
			{
				return this._CategoryDescription;
			}
			set
			{
				if ((this._CategoryDescription != value))
				{
					this._CategoryDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryImageFilename", DbType="NVarChar(200)")]
		public string CategoryImageFilename
		{
			get
			{
				return this._CategoryImageFilename;
			}
			set
			{
				if ((this._CategoryImageFilename != value))
				{
					this._CategoryImageFilename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPublished", DbType="Bit NOT NULL")]
		public bool IsPublished
		{
			get
			{
				return this._IsPublished;
			}
			set
			{
				if ((this._IsPublished != value))
				{
					this._IsPublished = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortIndex", DbType="Int")]
		public System.Nullable<int> SortIndex
		{
			get
			{
				return this._SortIndex;
			}
			set
			{
				if ((this._SortIndex != value))
				{
					this._SortIndex = value;
				}
			}
		}
	}
	
	public partial class ProductsListResult
	{
		
		private int _ProductID;
		
		private System.Nullable<int> _CategoryID;
		
		private string _CategoryCaption;
		
		private System.Nullable<int> _CategoryTheme;
		
		private string _ProductSlug;
		
		private string _ProductCaption;
		
		private System.Nullable<decimal> _ProductPrice;
		
		private System.Nullable<decimal> _ProductOldPrice;
		
		private string _ProductImageFilename;
		
		private bool _IsPublished;
		
		private System.DateTime _CRTime;
		
		public ProductsListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int NOT NULL")]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this._ProductID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID", DbType="Int")]
		public System.Nullable<int> CategoryID
		{
			get
			{
				return this._CategoryID;
			}
			set
			{
				if ((this._CategoryID != value))
				{
					this._CategoryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryCaption", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string CategoryCaption
		{
			get
			{
				return this._CategoryCaption;
			}
			set
			{
				if ((this._CategoryCaption != value))
				{
					this._CategoryCaption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryTheme", DbType="Int")]
		public System.Nullable<int> CategoryTheme
		{
			get
			{
				return this._CategoryTheme;
			}
			set
			{
				if ((this._CategoryTheme != value))
				{
					this._CategoryTheme = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductSlug", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ProductSlug
		{
			get
			{
				return this._ProductSlug;
			}
			set
			{
				if ((this._ProductSlug != value))
				{
					this._ProductSlug = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCaption", DbType="NVarChar(200)")]
		public string ProductCaption
		{
			get
			{
				return this._ProductCaption;
			}
			set
			{
				if ((this._ProductCaption != value))
				{
					this._ProductCaption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductPrice", DbType="Money")]
		public System.Nullable<decimal> ProductPrice
		{
			get
			{
				return this._ProductPrice;
			}
			set
			{
				if ((this._ProductPrice != value))
				{
					this._ProductPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductOldPrice", DbType="Money")]
		public System.Nullable<decimal> ProductOldPrice
		{
			get
			{
				return this._ProductOldPrice;
			}
			set
			{
				if ((this._ProductOldPrice != value))
				{
					this._ProductOldPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductImageFilename", DbType="NVarChar(200)")]
		public string ProductImageFilename
		{
			get
			{
				return this._ProductImageFilename;
			}
			set
			{
				if ((this._ProductImageFilename != value))
				{
					this._ProductImageFilename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPublished", DbType="Bit NOT NULL")]
		public bool IsPublished
		{
			get
			{
				return this._IsPublished;
			}
			set
			{
				if ((this._IsPublished != value))
				{
					this._IsPublished = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
	}
	
	public partial class UsersListResult
	{
		
		private int _UserID;
		
		private string _Email;
		
		private string _Password;
		
		private string _Firstname;
		
		private string _Lastname;
		
		private string _Fullname;
		
		private System.Nullable<System.DateTime> _Birthdate;
		
		private string _Mobile;
		
		private string _Avatar;
		
		private bool _IsActive;
		
		private System.DateTime _CRTime;
		
		public UsersListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="NVarChar(50)")]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this._Firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lastname", DbType="NVarChar(50)")]
		public string Lastname
		{
			get
			{
				return this._Lastname;
			}
			set
			{
				if ((this._Lastname != value))
				{
					this._Lastname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fullname", DbType="NVarChar(100)")]
		public string Fullname
		{
			get
			{
				return this._Fullname;
			}
			set
			{
				if ((this._Fullname != value))
				{
					this._Fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birthdate", DbType="Date")]
		public System.Nullable<System.DateTime> Birthdate
		{
			get
			{
				return this._Birthdate;
			}
			set
			{
				if ((this._Birthdate != value))
				{
					this._Birthdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="VarChar(20)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avatar", DbType="NVarChar(100)")]
		public string Avatar
		{
			get
			{
				return this._Avatar;
			}
			set
			{
				if ((this._Avatar != value))
				{
					this._Avatar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
	}
	
	public partial class OrderDetailsListResult
	{
		
		private int _OrderDetailID;
		
		private int _OrderID;
		
		private int _OrderDetailProductID;
		
		private string _ProductCaption;
		
		private int _OrderDetailProductCount;
		
		private System.Nullable<decimal> _OrderDetailProductPrice;
		
		private System.Nullable<decimal> _OrderDetailProductPricePaid;
		
		private System.Nullable<decimal> _OrderDetailProductPricePaidTotal;
		
		private string _ProductSlug;
		
		private string _ProductImageFilename;
		
		public OrderDetailsListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderDetailID", DbType="Int NOT NULL")]
		public int OrderDetailID
		{
			get
			{
				return this._OrderDetailID;
			}
			set
			{
				if ((this._OrderDetailID != value))
				{
					this._OrderDetailID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", DbType="Int NOT NULL")]
		public int OrderID
		{
			get
			{
				return this._OrderID;
			}
			set
			{
				if ((this._OrderID != value))
				{
					this._OrderID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderDetailProductID", DbType="Int NOT NULL")]
		public int OrderDetailProductID
		{
			get
			{
				return this._OrderDetailProductID;
			}
			set
			{
				if ((this._OrderDetailProductID != value))
				{
					this._OrderDetailProductID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCaption", DbType="NVarChar(200)")]
		public string ProductCaption
		{
			get
			{
				return this._ProductCaption;
			}
			set
			{
				if ((this._ProductCaption != value))
				{
					this._ProductCaption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderDetailProductCount", DbType="Int NOT NULL")]
		public int OrderDetailProductCount
		{
			get
			{
				return this._OrderDetailProductCount;
			}
			set
			{
				if ((this._OrderDetailProductCount != value))
				{
					this._OrderDetailProductCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderDetailProductPrice", DbType="Money")]
		public System.Nullable<decimal> OrderDetailProductPrice
		{
			get
			{
				return this._OrderDetailProductPrice;
			}
			set
			{
				if ((this._OrderDetailProductPrice != value))
				{
					this._OrderDetailProductPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderDetailProductPricePaid", DbType="Money")]
		public System.Nullable<decimal> OrderDetailProductPricePaid
		{
			get
			{
				return this._OrderDetailProductPricePaid;
			}
			set
			{
				if ((this._OrderDetailProductPricePaid != value))
				{
					this._OrderDetailProductPricePaid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderDetailProductPricePaidTotal", DbType="Money")]
		public System.Nullable<decimal> OrderDetailProductPricePaidTotal
		{
			get
			{
				return this._OrderDetailProductPricePaidTotal;
			}
			set
			{
				if ((this._OrderDetailProductPricePaidTotal != value))
				{
					this._OrderDetailProductPricePaidTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductSlug", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ProductSlug
		{
			get
			{
				return this._ProductSlug;
			}
			set
			{
				if ((this._ProductSlug != value))
				{
					this._ProductSlug = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductImageFilename", DbType="NVarChar(200)")]
		public string ProductImageFilename
		{
			get
			{
				return this._ProductImageFilename;
			}
			set
			{
				if ((this._ProductImageFilename != value))
				{
					this._ProductImageFilename = value;
				}
			}
		}
	}
	
	public partial class ProductsListFilteredResult
	{
		
		private System.Nullable<int> _ProductID;
		
		private System.Nullable<int> _CategoryID;
		
		private string _CategoryCaption;
		
		private System.Nullable<int> _CategoryTheme;
		
		private string _ProductSlug;
		
		private string _ProductCaption;
		
		private System.Nullable<decimal> _ProductPrice;
		
		private System.Nullable<decimal> _ProductOldPrice;
		
		private string _ProductImageFilename;
		
		public ProductsListFilteredResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int")]
		public System.Nullable<int> ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this._ProductID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID", DbType="Int")]
		public System.Nullable<int> CategoryID
		{
			get
			{
				return this._CategoryID;
			}
			set
			{
				if ((this._CategoryID != value))
				{
					this._CategoryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryCaption", DbType="NVarChar(200)")]
		public string CategoryCaption
		{
			get
			{
				return this._CategoryCaption;
			}
			set
			{
				if ((this._CategoryCaption != value))
				{
					this._CategoryCaption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryTheme", DbType="Int")]
		public System.Nullable<int> CategoryTheme
		{
			get
			{
				return this._CategoryTheme;
			}
			set
			{
				if ((this._CategoryTheme != value))
				{
					this._CategoryTheme = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductSlug", DbType="NVarChar(200)")]
		public string ProductSlug
		{
			get
			{
				return this._ProductSlug;
			}
			set
			{
				if ((this._ProductSlug != value))
				{
					this._ProductSlug = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCaption", DbType="NVarChar(200)")]
		public string ProductCaption
		{
			get
			{
				return this._ProductCaption;
			}
			set
			{
				if ((this._ProductCaption != value))
				{
					this._ProductCaption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductPrice", DbType="Money")]
		public System.Nullable<decimal> ProductPrice
		{
			get
			{
				return this._ProductPrice;
			}
			set
			{
				if ((this._ProductPrice != value))
				{
					this._ProductPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductOldPrice", DbType="Money")]
		public System.Nullable<decimal> ProductOldPrice
		{
			get
			{
				return this._ProductOldPrice;
			}
			set
			{
				if ((this._ProductOldPrice != value))
				{
					this._ProductOldPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductImageFilename", DbType="NVarChar(200)")]
		public string ProductImageFilename
		{
			get
			{
				return this._ProductImageFilename;
			}
			set
			{
				if ((this._ProductImageFilename != value))
				{
					this._ProductImageFilename = value;
				}
			}
		}
	}
	
	public partial class OrdersListResult
	{
		
		private int _OrderID;
		
		private int _OrderStatusID;
		
		private int _CustomerID;
		
		private string _Fullname;
		
		private string _ShippingFirstname;
		
		private string _ShippingLastname;
		
		private string _ShippingAddress1;
		
		private string _ShippingAddress2;
		
		private string _ShippingCity;
		
		private string _ShippingRegion;
		
		private System.Nullable<int> _ShippingCountryID;
		
		private string _ShippingZip;
		
		private string _BillingFirstname;
		
		private string _BillingLastname;
		
		private string _BillingAddress1;
		
		private string _BillingAddress2;
		
		private string _BillingCity;
		
		private string _BillingRegion;
		
		private System.Nullable<int> _BillingCountryID;
		
		private string _BillingZip;
		
		private string _Phone;
		
		private System.Nullable<decimal> _OrderPrice;
		
		private System.Nullable<decimal> _OrderPricePaid;
		
		private System.Nullable<decimal> _ShippingPrice;
		
		private System.Nullable<decimal> _OrderTotalPrice;
		
		private System.Nullable<System.DateTime> _OrderPaymentDateTime;
		
		private bool _IsOrderDelivered;
		
		private System.Nullable<int> _PaymentOptionID;
		
		private string _TransactionID;
		
		private System.DateTime _CRTime;
		
		public OrdersListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", DbType="Int NOT NULL")]
		public int OrderID
		{
			get
			{
				return this._OrderID;
			}
			set
			{
				if ((this._OrderID != value))
				{
					this._OrderID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderStatusID", DbType="Int NOT NULL")]
		public int OrderStatusID
		{
			get
			{
				return this._OrderStatusID;
			}
			set
			{
				if ((this._OrderStatusID != value))
				{
					this._OrderStatusID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int NOT NULL")]
		public int CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this._CustomerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fullname", DbType="NVarChar(100)")]
		public string Fullname
		{
			get
			{
				return this._Fullname;
			}
			set
			{
				if ((this._Fullname != value))
				{
					this._Fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingFirstname", DbType="NVarChar(100)")]
		public string ShippingFirstname
		{
			get
			{
				return this._ShippingFirstname;
			}
			set
			{
				if ((this._ShippingFirstname != value))
				{
					this._ShippingFirstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingLastname", DbType="NVarChar(100)")]
		public string ShippingLastname
		{
			get
			{
				return this._ShippingLastname;
			}
			set
			{
				if ((this._ShippingLastname != value))
				{
					this._ShippingLastname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingAddress1", DbType="NVarChar(100)")]
		public string ShippingAddress1
		{
			get
			{
				return this._ShippingAddress1;
			}
			set
			{
				if ((this._ShippingAddress1 != value))
				{
					this._ShippingAddress1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingAddress2", DbType="NVarChar(100)")]
		public string ShippingAddress2
		{
			get
			{
				return this._ShippingAddress2;
			}
			set
			{
				if ((this._ShippingAddress2 != value))
				{
					this._ShippingAddress2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingCity", DbType="NVarChar(50)")]
		public string ShippingCity
		{
			get
			{
				return this._ShippingCity;
			}
			set
			{
				if ((this._ShippingCity != value))
				{
					this._ShippingCity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingRegion", DbType="NVarChar(50)")]
		public string ShippingRegion
		{
			get
			{
				return this._ShippingRegion;
			}
			set
			{
				if ((this._ShippingRegion != value))
				{
					this._ShippingRegion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingCountryID", DbType="Int")]
		public System.Nullable<int> ShippingCountryID
		{
			get
			{
				return this._ShippingCountryID;
			}
			set
			{
				if ((this._ShippingCountryID != value))
				{
					this._ShippingCountryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingZip", DbType="NVarChar(50)")]
		public string ShippingZip
		{
			get
			{
				return this._ShippingZip;
			}
			set
			{
				if ((this._ShippingZip != value))
				{
					this._ShippingZip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingFirstname", DbType="NVarChar(100)")]
		public string BillingFirstname
		{
			get
			{
				return this._BillingFirstname;
			}
			set
			{
				if ((this._BillingFirstname != value))
				{
					this._BillingFirstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingLastname", DbType="NVarChar(100)")]
		public string BillingLastname
		{
			get
			{
				return this._BillingLastname;
			}
			set
			{
				if ((this._BillingLastname != value))
				{
					this._BillingLastname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingAddress1", DbType="NVarChar(100)")]
		public string BillingAddress1
		{
			get
			{
				return this._BillingAddress1;
			}
			set
			{
				if ((this._BillingAddress1 != value))
				{
					this._BillingAddress1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingAddress2", DbType="NVarChar(100)")]
		public string BillingAddress2
		{
			get
			{
				return this._BillingAddress2;
			}
			set
			{
				if ((this._BillingAddress2 != value))
				{
					this._BillingAddress2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingCity", DbType="NVarChar(50)")]
		public string BillingCity
		{
			get
			{
				return this._BillingCity;
			}
			set
			{
				if ((this._BillingCity != value))
				{
					this._BillingCity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingRegion", DbType="NVarChar(50)")]
		public string BillingRegion
		{
			get
			{
				return this._BillingRegion;
			}
			set
			{
				if ((this._BillingRegion != value))
				{
					this._BillingRegion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingCountryID", DbType="Int")]
		public System.Nullable<int> BillingCountryID
		{
			get
			{
				return this._BillingCountryID;
			}
			set
			{
				if ((this._BillingCountryID != value))
				{
					this._BillingCountryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingZip", DbType="NVarChar(50)")]
		public string BillingZip
		{
			get
			{
				return this._BillingZip;
			}
			set
			{
				if ((this._BillingZip != value))
				{
					this._BillingZip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderPrice", DbType="Money")]
		public System.Nullable<decimal> OrderPrice
		{
			get
			{
				return this._OrderPrice;
			}
			set
			{
				if ((this._OrderPrice != value))
				{
					this._OrderPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderPricePaid", DbType="Money")]
		public System.Nullable<decimal> OrderPricePaid
		{
			get
			{
				return this._OrderPricePaid;
			}
			set
			{
				if ((this._OrderPricePaid != value))
				{
					this._OrderPricePaid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingPrice", DbType="Money")]
		public System.Nullable<decimal> ShippingPrice
		{
			get
			{
				return this._ShippingPrice;
			}
			set
			{
				if ((this._ShippingPrice != value))
				{
					this._ShippingPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderTotalPrice", DbType="Money")]
		public System.Nullable<decimal> OrderTotalPrice
		{
			get
			{
				return this._OrderTotalPrice;
			}
			set
			{
				if ((this._OrderTotalPrice != value))
				{
					this._OrderTotalPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderPaymentDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> OrderPaymentDateTime
		{
			get
			{
				return this._OrderPaymentDateTime;
			}
			set
			{
				if ((this._OrderPaymentDateTime != value))
				{
					this._OrderPaymentDateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsOrderDelivered", DbType="Bit NOT NULL")]
		public bool IsOrderDelivered
		{
			get
			{
				return this._IsOrderDelivered;
			}
			set
			{
				if ((this._IsOrderDelivered != value))
				{
					this._IsOrderDelivered = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentOptionID", DbType="Int")]
		public System.Nullable<int> PaymentOptionID
		{
			get
			{
				return this._PaymentOptionID;
			}
			set
			{
				if ((this._PaymentOptionID != value))
				{
					this._PaymentOptionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionID", DbType="NVarChar(500)")]
		public string TransactionID
		{
			get
			{
				return this._TransactionID;
			}
			set
			{
				if ((this._TransactionID != value))
				{
					this._TransactionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
